services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meilisearch-manager
    entrypoint: /bin/sh
    working_dir: /workspace
    volumes:
      - '.:/workspace'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch-manager.rule=Host(`meilisearch-manager.localhost`)"
      - "traefik.http.services.meilisearch-manager.loadbalancer.server.port=${VITE_APP_PORT:-5173}"
    networks:
      - proxy

networks:
  proxy: # setup in separate container
    name: "traefik_network"
    external: true
